const modalObj = [
	{
		id: 'modalBasic01',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardDuration: 0,
			backwardDuration: 0,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0, 
			x: 0, 
			y: 0,
		}
	},
	{
		id: 'modalBasic02',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'opacity',
			forwardDuration: 0.3,
			backwardDuration: 0.3,
			delay: 0,
			forwardEasing: 'ease-out', 
			backwardEasing: 'ease-out',
			initXPercent: 0, 
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0, 
			x: 0, 
			y: 0,
		},
	},
	{
		id: 'modalSlide01',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardDuration: 0.3,
			backwardDuration: 0,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			initXPercent: 0,
			initYPercent: 200,
			backwardXPercent: 0,
			backwardYPercent: 0,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide02',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'return',
			forwardDuration: 0.3,
			backwardDuration: 0.25,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			initXPercent: 0,
			initYPercent: 200,
			backwardXPercent: 0,
			backwardYPercent: 200,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide03',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'opacity',
			forwardDuration: 0.3,
			backwardDuration: 0.3,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			initXPercent: 0,
			initYPercent: 200,
			backwardXPercent: 0,
			backwardYPercent: 20,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide04',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardDuration: 0.3,
			backwardDuration: 0,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			initXPercent: 0,
			initYPercent: 20,
			backwardXPercent: 0,
			backwardYPercent: 0,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide05',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'opacity',
			forwardDuration: 0.3,
			backwardDuration: 0.3,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			initXPercent: 0,
			initYPercent: 20,
			backwardXPercent: 0,
			backwardYPercent: 20,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide06',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardDuration: 0.3,
			backwardDuration: 0,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			initXPercent: 200,
			initYPercent: 0,
			backwardXPercent: 0,
			backwardYPercent: 0,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide07',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'opacity',
			forwardDuration: 0.3,
			backwardDuration: 0.25,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			initXPercent: 200,
			initYPercent: 0,
			backwardXPercent: 20,
			backwardYPercent: 0,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide08',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'return',
			forwardDuration: 0.3,
			backwardDuration: 0.25,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			initXPercent: 200,
			initYPercent: 0,
			backwardXPercent: 200,
			backwardYPercentt: 0,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide09',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardDuration: 0.3,
			backwardDuration: 0,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			initXPercent: 20,
			initYPercent: 0,
			backwardXPercent: 0,
			backwardYPercent: 0,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalSlide10',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'opacity',
			forwardDuration: 0.3,
			backwardDuration: 0.25,
			delay: 0,
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			initXPercent: 20,
			initYPercent: 0,
			backwardXPercent: 20,
			backwardYPercent: 0,
			x: 0,
			y: 0,
		}
	},
	{
		id: 'modalScale01',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: '',
			forwardDuration: 0.3,
			backwardDuration: 0,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
		
			initScale: 0,
			backwardScale: 0,
		}
	},
	{
		id: 'modalScale02',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'return',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			forwardDuration: 0.3,
			backwardDuration: 0.25,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0,
			y: 0,
		
			initScale: 0,
			backwardScale: 0,
		}
	},
	{
		id: 'modalScale03',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'opacity',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			forwardDuration: 0.3,
			backwardDuration: 0.25,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
		
			initScale: 0,
			backwardScale: 0.8,
		}
	},
	{
		id: 'modalScale04',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: '',
			forwardDuration: 0.3,
			backwardDuration: 0,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
		
			initScale: 1.2,
			backwardScale: 1.2,
		}
	},
	{
		id: 'modalScale05',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'return',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			forwardDuration: 0.3,
			backwardDuration: 0.25,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0,
			y: 0,
		
			initScale: 1.2,
			backwardScale: 1.2,
		}
	},
	{
		id: 'modalScale06',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'opacity',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			forwardDuration: 0.3,
			backwardDuration: 0.25,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
		
			initScale: 1.2,
			backwardScale: 1,
		}
	},
	{
		id: 'modalBounce01',
		constructor: '.modal-wrap',
		option: {
			name: 'bounce',
			dimm: true,
			type: 'normal',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: '',
			forwardDuration: 0.08,
			backwardDuration: 0,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
		
			initScale: 0,
			backwardScale: 1,
			scaleProgress: {
				0: {x: 0, y: 0}, // 진행률 0%
				50: {x: 1.03, y: 1.03}, // 진행률 50%
				75: {x: 0.99, y: 0.99}, // 진행률 75%
				100: {x: 1, y: 1} // 진행률 100%
			},
		}
	},
	{
		id: 'modalBounce02',
		constructor: '.modal-wrap',
		option: {
			name: 'bounce',
			dimm: true,
			type: 'normal',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			forwardDuration: 0.08,
			backwardDuration: 0.25,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
		
			initScale: 0,
			backwardScale: 0,
			scaleProgress: {
				0: {x: 0, y: 0}, // 진행률 0%
				50: {x: 1.03, y: 1.03}, // 진행률 50%
				75: {x: 0.99, y: 0.99}, // 진행률 75%
				100: {x: 1, y: 1} // 진행률 100%
			},
		}
	},
	{
		id: 'modalBounce03',
		constructor: '.modal-wrap',
		option: {
			name: 'bounce',
			dimm: true,
			type: 'normal',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'linear',
			forwardDuration: 0.08,
			backwardDuration: 0.25,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
		
			initScale: 0,
			backwardScale: 1,
			scaleProgress: {
				0: {x: 0, y: 0}, // 진행률 0%
				50: {x: 1.03, y: 1.03}, // 진행률 50%
				75: {x: 0.99, y: 0.99}, // 진행률 75%
				100: {x: 1, y: 1} // 진행률 100%
			},
		}
	},
	{
		id: 'modal3d01',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: '',
			forwardDuration: 0.5,
			backwardDuration: 0,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
		
			initScale: 1,
			backwardScale: 1,
			rotateX: 0,
			rotateY: -70,
			backwardRotateX: 0,
			backwardRotateY: -70,
			transformPerspective: 1800,
		}
	},
	{
		id: 'modal3d02',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'return',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			forwardDuration: 0.5,
			backwardDuration: 0.3,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
			initScale: 1,
			backwardScale: 1,
			rotateX: 0,
			rotateY: -70,
			backwardRotateX: 0,
			backwardRotateY: -70,
			transformPerspective: 1800,
		}
	},
	{
		id: 'modal3d03',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'disrotatory',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			forwardDuration: 0.5,
			backwardDuration: 0.3,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
			initScale: 1,
			backwardScale: 1,
			rotateX: 0,
			rotateY: -70,
			backwardRotateX: 0,
			backwardRotateY: 70,
			transformPerspective: 1800,
		}
	},
	{
		id: 'modal3d04',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'normal',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: '',
			forwardDuration: 0.5,
			backwardDuration: 0,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
			initScale: 1,
			backwardScale: 1,
			rotateX: -70,
			rotateY: 0,
			backwardRotateX: 0,
			backwardRotateY: 0,
			transformPerspective: 1800,
		}
	},
	{
		id: 'modal3d05',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'return',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			forwardDuration: 0.5,
			backwardDuration: 0.3,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
			initScale: 1,
			backwardScale: 1,
			rotateX: -70,
			rotateY: 0,
			backwardRotateX: -70,
			backwardRotateY: 0,
			transformPerspective: 1800,
		}
	},
	{
		id: 'modal3d06',
		constructor: '.modal-wrap',
		option: {
			dimm: true,
			type: 'disrotatory',
			forwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			backwardEasing: 'cubic-bezier(0.22, 1, 0.36, 1)',
			forwardDuration: 0.5,
			backwardDuration: 0.3,
			delay: 0,
			initXPercent: 0,
			initYPercent: 0, 
			backwardXPercent: 0, 
			backwardYPercent: 0,
			x: 0, 
			y: 0,
			initScale: 1,
			backwardScale: 1,
			rotateX: -70,
			rotateY: 0,
			backwardRotateX: 70,
			backwardRotateY: 0,
			transformPerspective: 1800,
		}
	},
]

export default modalObj